language: php

php:
    - 7.1

install:
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry vendor/bin/coveralls -v