language: php

php:
    - 7.3

install:
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - vendor/bin/phpcs tests src --standard=PSR2
    - vendor/bin/phpstan analyse -l max src
