language: php

php:
    - 7.1
    - 7.2

install:
    - composer install
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - vendor/bin/phpcs tests src --standard=PSR2

after_success:
    - travis_retry vendor/bin/php-coveralls -v
